using FluentMigrator;
using PetDiary.Persistence.Common;

namespace PetDiary.Persistence.Migrations
{
    [Migration(5, "Sticker Pack table")]
    public class StickerPackTable : SqlMigration
    {
        protected override string GetUpSql(IServiceProvider services) => @"
    create table stickerpacks(

    id	bigint generated by default as identity
        constraint pk_stickerpacks
            primary key,
	
    title text
    
);
";

        protected override string GetDownSql(IServiceProvider services) => @"
drop table if exists stickerspacks;";

    }
}