using FluentMigrator;
using PetDiary.Persistence.Common;

namespace PetDiary.Persistence.Migrations;

[Migration(6, "sticker table")]
public class StickersTable : SqlMigration
{
    protected override string GetUpSql(IServiceProvider services) => @"
    create table stickers(

    id	bigint generated by default as identity
        constraint pk_stickers
            primary key,
	
    sticker_pack_id bigint not null
        constraint fk_stickers__stickerpacks_id
            references stickers
            on delete cascade,
        
    base_64_image text
    
    
);
";

    protected override string GetDownSql(IServiceProvider services) => @"
drop table if exists stickers;";

}