using FluentMigrator;
using PetDiary.Persistence.Common;

namespace PetDiary.Persistence.Migrations;

[Migration(7, "diaries table")]
public class DiariesTable : SqlMigration
{
    protected override string GetUpSql(IServiceProvider services) => $@"
    
    create table diaries(
        
        id bigint not null generated by default as identity
            constraint pk_diaries
            primary key,

        user_id bigint not null
            constraint fk_diaries__user_profiles_id
            references user_profiles
            on delete cascade,

        title text,
        description text,
        diary_type bigint not null

);
";

    protected override string GetDownSql(IServiceProvider services) => $@"
    drop table if exists diaries;
";
}
