using FluentMigrator;
using PetDiary.Persistence.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PetDiary.Persistence.Migrations;

[Migration(7, "diaries table")]
public class DiariesTable : SqlMigration
{
    protected override string GetDownSql(IServiceProvider services) => $@"
    
    create table diaries(
        
        id big int not null generated by default as identity
            constraint pk_diaries
            primary key,

        title text,
        description text,
        diary_type bigint not null

);
";

    protected override string GetUpSql(IServiceProvider services) => $@"
    drop table if exists diaries;
";
}
