using FluentMigrator;
using PetDiary.Persistence.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PetDiary.Persistence.Migrations;

[Migration(8, "diaries table")]
public class NotesTable : SqlMigration
{
    protected override string GetDownSql(IServiceProvider services) => $@"
    
    create table notes(
        
        id big int not null generated by default as identity
            constraint pk_notes
            primary key,

        title text,
        content text,
        diary_id bigint not null
            constraint fk_notes__diaries_id
            references diaries
            on delete cascade
);
";

    protected override string GetUpSql(IServiceProvider services) => $@"
    drop table if exists notes;
";
}
