using FluentMigrator;
using PetDiary.Persistence.Common;

namespace PetDiary.Persistence.Migrations
{

    [Migration(8, "notes table")]
    public class NotesTable : SqlMigration
    {
        protected override string GetUpSql(IServiceProvider services) => $@"
    create table notes(
        id bigint not null generated by default as identity
            constraint pk_notes
            primary key,

        title text,
        content text,
        diary_id bigint not null
            constraint fk_notes__diaries_id
            references diaries
            on delete cascade
);
";

        protected override string GetDownSql(IServiceProvider services) => $@"
    drop table if exists notes;
";
    }
}