using FluentMigrator;
using PetDiary.Persistence.Common;

namespace PetDiary.Persistence.Migrations
{

    [Migration(9, "pasted stickers table")]
    public class PastedStickersTable : SqlMigration
    {
        protected override string GetUpSql(IServiceProvider services) => $@"
    create table pasted_stickers(
        
        id bigint not null generated by default as identity
            constraint pk_pasted_stickers
            primary key,

        note_id bigint not null
            constraint fk_pasted_stickers__notes_note_id
            references notes,

        sticker_id bigint not null
            constraint fk_pasted_stickers__stickers_sticker_id
            references stickers
            on delete cascade,
        
        x_axis_indentation decimal not null,
        y_axis_indentation decimal not null,
        rotate_corner decimal not null
        
);
";

        protected override string GetDownSql(IServiceProvider services) => $@"
    drop table if exists pasted_stickers;
";
    }
}
