using FluentMigrator;
using PetDiary.Persistence.Common;

namespace PetDiary.Persistence.Migrations
{
    [Migration(10, "user settings table")]
    public class UserSettings : SqlMigration
    {
        protected override string GetUpSql(IServiceProvider services) => $@"
    
    create table user_settings(
        
        id bigint not null generated by default as identity
            constraint pk_user_settings
            primary key,

        user_id bigint not null
            constraint fk_user_settings__user_profiles_id
            references user_profiles,

        font bigint not null,
        ApplicationTheme bigint not null
);
";

        protected override string GetDownSql(IServiceProvider services) => $@"
    drop table if exists user_settings;
";
    }
}
