using FluentMigrator;
using PetDiary.Persistence.Common;

namespace PetDiary.Persistence.Migrations
{
    [Migration(11, "comments table")]
    public class CommentsTable : SqlMigration
    {
        protected override string GetUpSql(IServiceProvider services) => $@"
    
    create table comments(
        
        id big int not null generated by default as identity
            constraint pk_comments
            primary key,

        content text,
        
        
        note_id bigint not null
            constraint fk_comments__notes_id
            references notes,

        writer_id bigint not null
            constraint fk_comments__user_profiles_id
            references user_profiles,
       
        
);
";

        protected override string GetDownSql(IServiceProvider services) => $@"
    drop table if exists comments;
";
    }
}
